[tool.djlint]
# ignore = "W013"
extension = "html"
indent = "\t" # change indentation level
exclude = ".venv,venv,.eggs" # override the default set of excluded paths

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "urbanvitaliz.settings.development"
addopts = "--reuse-db --tb=short -p no:warnings -n auto --maxprocesses 4"
# addopts = "--cov=urbanvitaliz --cov=test --cov-report=xml --reuse-db --tb=short -p no:warnings -n auto --maxprocesses 4"
testpaths = [
    "urbanvitaliz"
]
python_files = "tests.py test_*.py *_test.py *_tests.py"

[tool.pylint.main]
jobs = 2
load-plugins = "pylint_django"
ignore = ["settings","static","templates",".venv","tests", "migrations"]
disable = [
        "missing-function-docstring",
        "missing-class-docstring",
        "missing-module-docstring",
        "use-list-literal",
        "use-dict-literal",
        "duplicate-code",
        "possibly-unused-variable",  # django views w/ locals()
        "consider-using-f-string",
        "fixme",
]

[tool.pylint.design]
min-public-methods = 1


