[tool.djlint]
# ignore = "W013"
extension = "html"
indent = 4
exclude = ".venv,venv,.eggs" # override the default set of excluded paths

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "recoco.settings.development"
addopts = "--reuse-db --tb=short -p no:warnings -n auto --maxprocesses 4"
# addopts = "--cov=recoco --cov=test --cov-report=xml --reuse-db --tb=short -p no:warnings -n auto --maxprocesses 4"
testpaths = ["recoco"]
python_files = "tests.py test_*.py *_test.py *_tests.py"

[tool.pylint.main]
jobs = 2
load-plugins = "pylint_django"
good-names-rgxs = "^[_a-z][_a-z0-9]?$"
ignore = ["settings", "static", "templates", ".venv", "tests", "migrations"]
disable = [
    "missing-function-docstring",
    "missing-class-docstring",
    "missing-module-docstring",
    "use-list-literal",
    "use-dict-literal",
    "duplicate-code",
    "possibly-unused-variable",   # django views w/ locals()
    "consider-using-f-string",
    "fixme",
]

[tool.pylint.design]
min-public-methods = 1

[tool.bandit]
exclude_dirs = ['node_modules']

[tool.bandit.assert_used]
skips = ['*_test.py', '**/test_*.py', '**/tests.py']

[tool.ruff.lint]
select = [
    "E4",
    "E7",
    "E9",
    "B",  # flake8-bugbear
    "F",  # Pyflakes
    "I",  # isort
]
unfixable = ["ALL"]
fixable = ["I"]

[tool.ruff.lint.isort]
case-sensitive = true
known-third-party = [
    "crispy_forms",
    "django",
    "dotenv",
    "fabric",
    "factory",
    "guardian",
    "IPython",
    "ipywidgets",
    "model_bakery",
    "requests",
    "rest_framework",
]
split-on-trailing-comma = true
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]

[tool.ruff.lint.extend-per-file-ignores]
"notebooks/*.py" = ["E402", "F821"]
"**/migrations/*.py" = ["I"]
